---
- name: Deploy RedditTitleSentiment Flask app and API (isolated venvs)
  hosts: webservers
  become: yes
  vars:
    repo_url: "https://github.com/YOUR_USERNAME/RedditTitleSentiment.git"
    repo_dest: /opt/RedditTitleSentiment
    app_user: flaskuser

    # Virtual environment paths
    venv_app: /opt/RedditTitleSentiment/venv_app
    venv_api: /opt/RedditTitleSentiment/venv_api

    flask_server_path: "{{ repo_dest }}/flask_server"
    gunicorn_socket: /run/gunicorn.sock
    frontend_service: flask_server_gunicorn
    api_service: flask_api_gunicorn

    # Requirements for each component
    app_py_reqs:
      - flask
      - flask_sqlalchemy
      - gunicorn
      - praw
      - beautifulsoup4
      - requests
    api_py_reqs:
      - flask
      - gunicorn
      - transformers
      - torch
      - mlflow

  tasks:
    - name: Ensure required apt packages are installed
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - nginx
          - git
        update_cache: yes

    - name: Ensure application user exists
      user:
        name: "{{ app_user }}"
        system: yes
        create_home: yes

    - name: Clone the RedditTitleSentiment repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        update: yes
        version: main

    - name: Create virtual environment for app.py
      command: python3 -m venv "{{ venv_app }}"
      args:
        creates: "{{ venv_app }}/bin/activate"

    - name: Create virtual environment for api.py
      command: python3 -m venv "{{ venv_api }}"
      args:
        creates: "{{ venv_api }}/bin/activate"

    - name: Install app.py requirements
      pip:
        name: "{{ app_py_reqs }}"
        virtualenv: "{{ venv_app }}"

    - name: Install api.py requirements
      pip:
        name: "{{ api_py_reqs }}"
        virtualenv: "{{ venv_api }}"

    - name: Set Reddit API environment variables
      copy:
        dest: /etc/environment
        content: |
          REDDIT_CLIENT_ID="{{ lookup('env', 'REDDIT_CLIENT_ID') }}"
          REDDIT_CLIENT_SECRET="{{ lookup('env', 'REDDIT_CLIENT_SECRET') }}"
          REDDIT_USER_AGENT="{{ lookup('env', 'REDDIT_USER_AGENT') }}"
      notify: Reload Environment

    - name: Create systemd service for frontend (app.py)
      copy:
        dest: /etc/systemd/system/{{ frontend_service }}.service
        content: |
          [Unit]
          Description=Flask App Frontend (app.py) via Gunicorn
          After=network.target

          [Service]
          User={{ app_user }}
          Group=www-data
          WorkingDirectory={{ flask_server_path }}
          EnvironmentFile=/etc/environment
          Environment="PATH={{ venv_app }}/bin"
          ExecStart={{ venv_app }}/bin/gunicorn -w 3 -b unix:{{ gunicorn_socket }} app:app

          [Install]
          WantedBy=multi-user.target

    - name: Create systemd service for API (api.py)
      copy:
        dest: /etc/systemd/system/{{ api_service }}.service
        content: |
          [Unit]
          Description=Flask API (api.py) via Gunicorn on localhost:5001
          After=network.target

          [Service]
          User={{ app_user }}
          Group=www-data
          WorkingDirectory={{ flask_server_path }}
          EnvironmentFile=/etc/environment
          Environment="PATH={{ venv_api }}/bin"
          ExecStart={{ venv_api }}/bin/gunicorn -w 2 -b 127.0.0.1:5001 api:app

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd and start services
      systemd:
        name: "{{ item }}"
        daemon_reload: yes
        enabled: yes
        state: restarted
      loop:
        - "{{ frontend_service }}"
        - "{{ api_service }}"

    - name: Configure nginx for frontend
      copy:
        dest: /etc/nginx/sites-available/flask_server
        content: |
          server {
              listen 80;
              server_name _;

              location / {
                  proxy_pass http://unix:{{ gunicorn_socket }};
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }

              location /static/ {
                  alias {{ flask_server_path }}/static/;
              }
          }

    - name: Enable nginx site
      file:
        src: /etc/nginx/sites-available/flask_server
        dest: /etc/nginx/sites-enabled/flask_server
        state: link
        force: yes

    - name: Remove default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart nginx
      service:
        name: nginx
        state: restarted

    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Allow SSH
      ufw:
        rule: allow
        name: 'SSH'

    - name: Allow OpenSSH (redundant but safe)
      ufw:
        rule: allow
        name: 'OpenSSH'

    - name: Allow Nginx Full
      ufw:
        rule: allow
        name: 'Nginx Full'

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny
        logging: on

  handlers:
    - name: Reload Environment
      command: systemctl daemon-reexec
