---
- name: Set up MLflow on middleware-server
  hosts: middleware
  become: yes

  vars_files:
    - group_vars/middleware.yml

  vars:
    flask_server_ip: "{{ lookup('ini', 'flask-server  section=flask_server file=../infrastructure/inventory.ini') }}"

  tasks:
    - name: Install system dependencies
      apt:
        name:
          - python3-pip
          - python3-venv
          - git
          - unzip
          - ufw
        update_cache: yes

    - name: Create mlflow user
      user:
        name: mlflow
        create_home: yes
        shell: /bin/bash

    - name: Create MLflow application directory
      file:
        path: /opt/mlflow
        state: directory
        owner: mlflow
        group: mlflow
        mode: "0755"

    - name: Set up Python virtual environment
      command: python3 -m venv /opt/mlflow/venv
      creates: /opt/mlflow/venv

    - name: Upgrade pip inside virtualenv
      pip:
        name: pip
        state: latest
        virtualenv: /opt/mlflow/venv

    - name: Install required Python modules inside virtualenv
      pip:
        virtualenv: /opt/mlflow/venv
        name:
          - mlflow
          - boto3

    - name: Ensure MLflow log directory exists
      file:
        path: /var/log/mlflow
        state: directory
        owner: mlflow
        group: mlflow
        mode: "0755"

    - name: Configure UFW - Allow OpenSSH
      ufw:
        rule: allow
        name: OpenSSH

    - name: Configure UFW - Allow MLflow port for Flask server only
      ufw:
        rule: allow
        proto: tcp
        port: "{{ mlflow_port }}"
        from_ip: "{{ flask_server_ip }}"

    - name: Enable UFW
      ufw:
        state: enabled
        logging: 'on'

    - name: Create MLflow systemd service
      copy:
        dest: /etc/systemd/system/mlflow.service
        content: |
          [Unit]
          Description=MLflow Tracking Server
          After=network.target

          [Service]
          User=mlflow
          WorkingDirectory=/opt/mlflow
          ExecStart=/opt/mlflow/venv/bin/mlflow server \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root s3://{{ artifact_bucket }} \
            --host 0.0.0.0 \
            --port {{ mlflow_port }} \
            >> /var/log/mlflow/mlflow.log 2>&1
          Environment=MLFLOW_S3_ENDPOINT_URL={{ s3_endpoint }}
          Environment=AWS_ACCESS_KEY_ID={{ do_spaces_access_key_id }}
          Environment=AWS_SECRET_ACCESS_KEY={{ do_spaces_secret_access_key }}
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start MLflow service
      systemd:
        name: mlflow
        enabled: yes
        state: started
